### ISSUE TITLE
release scram-sha-256-linux-arm64 - naming error?

### ISSUE THREAD

**Issue by dulhaver** [supercaracal/scram-sha-256#6]
I believe this relase **[scram-sha-256-linux-arm64](https://github.com/supercaracal/scram-sha-256/releases)** might have a wrong name and should read "scram-sha-256-linux-**amd64**" (**amd**64, not **arm**64) instead.

**Comment by supercaracal** [comment]
I use [GoReleaser](https://github.com/goreleaser/goreleaser) with the following settings.
https://github.com/supercaracal/scram-sha-256/blob/675ce0375e96a22723eb0551eb7ed4676672155a/.goreleaser.yaml#L26-L31

Did something wrong occur with your environment?

e.g.

> cannot execute binary file: Exec format error

**Comment by dulhaver** [comment]
my point is the name of the release "scram-sha-256-linux-**arm64**"
arm64 indicates it was for arm processors. At the same time there is no release for **amd64** architecture. So I was guessing that maybe the naming was not correct.

Maybe that was a wrong assumption on my side and all Linux (Intel or AMD platform) are supposed to use the 
scram-sha-256-**linux-x86_64** (32 Bit I believe) release, even on amd64 machines. 

Is that so?

**Comment by supercaracal** [comment]
Yes, it is. Intel or AMD platform can use `x86_64` named file. But 32-bit machines are not supported.
