### ISSUE TITLE
Ability to use this as library

### ISSUE THREAD

**Issue by ChrisJBurns** [supercaracal/scram-sha-256#8]
To be able to use this in Go programs, can you make this usable as a lib? Preferably just allowing the `encryptPassword` to be called providing a user passes in the password to hash?

**Comment by supercaracal** [comment]
Now we can use it like this:

```go
import "github.com/supercaracal/scram-sha-256/pkg/pgpasswd"

func foo(rawPassword []byte) error {
    encrypted, err := pgpasswd.Encrypt(rawPassword)
    if err != nil {
        // ...
    }

    // ...
}
```
